### ISSUE TITLE
Cyhy-feeds depends on cyhy-core

### ISSUE THREAD

**Issue by KyleEvers** [jsf9k/cyhy-feeds#17]
cyhy-feeds depends on cyhy-core which is currently in a private repository. This causes two issues currently:
1. This means cyhy-feeds cannot be installed by anybody without anybody without access to the private cyhy-core repo
2. cyhy-feeds has to be run as Python 2 (cyhy-core is Python 2)

These issues should be solved my making cyhy-core public and moving cyhy-core to Python 3

**Comment by dav3r** [comment]
This issue can now be solved relatively easily by replacing the private `cyhy-core` dependency with our public [mongo-db-from-config](https://github.com/cisagov/mongo-db-from-config) library.

**Comment by mcdonnnj** [comment]
This issue was resolved in #26
