### ISSUE TITLE
Only keep "x" number of extracts in the S3 bucket

### ISSUE THREAD

**Issue by KyleEvers** [jsf9k/cyhy-feeds#23]
Currently cyhy-feeds does not delete any of the Archives in the S3 bucket. It should delete the oldest archive once the number of archives in the bucket is greater than a specified amount. The code for this was started and can be seen here: 
https://github.com/cisagov/cyhy-feeds/blob/develop/aws_jobs/cyhy-data-extract.py#L88-L100
Note: This code is still using the aws keys to access the bucket and not instance level policies like what feeds currently uses to authenticate to the bucket.

**Comment by mcdonnnj** [comment]
This has been resolved by #32 to offer a flag that will delete any output object in the bucket that is older than the configured retention time.
